### PR TITLE
Release 0.7.1.

### PR DESCRIPTION
**Pull request by hugopl**
If no one objects, I will do this minor release this weekend.

### CODE REVIEW

**Comment by mperham** [comment]
Would you be interested in forking and owning this repo? I haven't worked with Crystal in 5+ years and should step down as a maintainer.

**Comment by hugopl** [comment]
> Would you be interested in forking and owning this repo? I haven't worked with Crystal in 5+ years and should step down as a maintainer.

I already have a fork, so I think I need to remove my fork (to avoid conflicts), then you transfer the ownership of this repo to me, so issues, PRs, etc get transferred as well... besides the github taking care to do the proper URL redirections.

So, yes, I accept to own it. Not sure what we should do with the project name, since Sidekiq is your trademark so maybe change the project name would be a good thing to make a clear distinction from this project and your company... or maybe the explicit text in the README is enough... you say what would work.

**Comment by mperham** [comment]
I don't have any issues with the naming, given that I started the project. I do own the trademark but as long as this project doesn't change substantially or sell a commercial product, I have no problem. You are welcome to collect GitHub Sponsors to pay for ongoing maintenance, for instance.

**Comment by mperham** [comment]
You will need to remove your existing fork.

**Comment by hugopl** [comment]
Ok then. I removed my fork.

**Comment by hugopl** [comment]
Oops, I thought the transfer would be automatic (what makes no sense), but I need to accept it... and only saw the email today when the transfer expired, could you do it again? Sorry.

**Comment by hugopl** [comment]
Move successfully done, thanks.

**Pull request merged**
